services:
  hystron:
    image: ghcr.io/bx-team/hystron:${HYSTRON_VERSION:-latest}
    container_name: hystron
    restart: unless-stopped
    ports:
      - "${PUBLIC_PORT:-9000}:9000"
      - "${INTERNAL_PORT:-9001}:9001"
    volumes:
      - /var/lib/hystron:/var/lib/hystron
    environment:
      - HYST_DB_PATH=/var/lib/hystron/app.db
