FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
        python3 \
    && rm -rf /var/lib/apt/lists/*

ARG TARGETARCH
COPY files/xray-${TARGETARCH} /usr/local/bin/xray
RUN chmod +x /usr/local/bin/xray

COPY docker/node/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

VOLUME /etc/xray

EXPOSE 443/tcp 443/udp 10085/tcp 10086/tcp

ENTRYPOINT ["/entrypoint.sh"]
