# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: xray_api.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'xray_api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0exray_api.proto\x12\x08xray_api\"M\n\x13\x41lterInboundRequest\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12)\n\toperation\x18\x02 \x01(\x0b\x32\x16.xray_api.TypedMessage\"\x16\n\x14\x41lterInboundResponse\"3\n\x11QueryStatsRequest\x12\x0f\n\x07pattern\x18\x01 \x01(\t\x12\r\n\x05reset\x18\x02 \x01(\x08\"2\n\x12QueryStatsResponse\x12\x1c\n\x04stat\x18\x01 \x03(\x0b\x32\x0e.xray_api.Stat\"#\n\x04Stat\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03\"+\n\x0cTypedMessage\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\"M\n\x04User\x12\r\n\x05level\x18\x01 \x01(\r\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\'\n\x07\x61\x63\x63ount\x18\x03 \x01(\x0b\x32\x16.xray_api.TypedMessage\"0\n\x10\x41\x64\x64UserOperation\x12\x1c\n\x04user\x18\x01 \x01(\x0b\x32\x0e.xray_api.User\"$\n\x13RemoveUserOperation\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"(\n\x0cVlessAccount\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x66low\x18\x05 \x01(\t\"!\n\rTrojanAccount\x12\x10\n\x08password\x18\x01 \x01(\t\"\x1e\n\nHy2Account\x12\x10\n\x08password\x18\x01 \x01(\t2_\n\x0eHandlerService\x12M\n\x0c\x41lterInbound\x12\x1d.xray_api.AlterInboundRequest\x1a\x1e.xray_api.AlterInboundResponse2W\n\x0cStatsService\x12G\n\nQueryStats\x12\x1b.xray_api.QueryStatsRequest\x1a\x1c.xray_api.QueryStatsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xray_api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ALTERINBOUNDREQUEST']._serialized_start=28
  _globals['_ALTERINBOUNDREQUEST']._serialized_end=105
  _globals['_ALTERINBOUNDRESPONSE']._serialized_start=107
  _globals['_ALTERINBOUNDRESPONSE']._serialized_end=129
  _globals['_QUERYSTATSREQUEST']._serialized_start=131
  _globals['_QUERYSTATSREQUEST']._serialized_end=182
  _globals['_QUERYSTATSRESPONSE']._serialized_start=184
  _globals['_QUERYSTATSRESPONSE']._serialized_end=234
  _globals['_STAT']._serialized_start=236
  _globals['_STAT']._serialized_end=271
  _globals['_TYPEDMESSAGE']._serialized_start=273
  _globals['_TYPEDMESSAGE']._serialized_end=316
  _globals['_USER']._serialized_start=318
  _globals['_USER']._serialized_end=395
  _globals['_ADDUSEROPERATION']._serialized_start=397
  _globals['_ADDUSEROPERATION']._serialized_end=445
  _globals['_REMOVEUSEROPERATION']._serialized_start=447
  _globals['_REMOVEUSEROPERATION']._serialized_end=483
  _globals['_VLESSACCOUNT']._serialized_start=485
  _globals['_VLESSACCOUNT']._serialized_end=525
  _globals['_TROJANACCOUNT']._serialized_start=527
  _globals['_TROJANACCOUNT']._serialized_end=560
  _globals['_HY2ACCOUNT']._serialized_start=562
  _globals['_HY2ACCOUNT']._serialized_end=592
  _globals['_HANDLERSERVICE']._serialized_start=594
  _globals['_HANDLERSERVICE']._serialized_end=689
  _globals['_STATSSERVICE']._serialized_start=691
  _globals['_STATSSERVICE']._serialized_end=778
# @@protoc_insertion_point(module_scope)
