# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.xray.proto import xray_api_pb2 as xray__api__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in xray_api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HandlerServiceStub(object):
    """── HandlerService ──────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AlterInbound = channel.unary_unary(
                '/xray_api.HandlerService/AlterInbound',
                request_serializer=xray__api__pb2.AlterInboundRequest.SerializeToString,
                response_deserializer=xray__api__pb2.AlterInboundResponse.FromString,
                _registered_method=True)


class HandlerServiceServicer(object):
    """── HandlerService ──────────────────────────────────────────────────────────

    """

    def AlterInbound(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HandlerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AlterInbound': grpc.unary_unary_rpc_method_handler(
                    servicer.AlterInbound,
                    request_deserializer=xray__api__pb2.AlterInboundRequest.FromString,
                    response_serializer=xray__api__pb2.AlterInboundResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xray_api.HandlerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('xray_api.HandlerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HandlerService(object):
    """── HandlerService ──────────────────────────────────────────────────────────

    """

    @staticmethod
    def AlterInbound(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xray_api.HandlerService/AlterInbound',
            xray__api__pb2.AlterInboundRequest.SerializeToString,
            xray__api__pb2.AlterInboundResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class StatsServiceStub(object):
    """── StatsService ─────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueryStats = channel.unary_unary(
                '/xray_api.StatsService/QueryStats',
                request_serializer=xray__api__pb2.QueryStatsRequest.SerializeToString,
                response_deserializer=xray__api__pb2.QueryStatsResponse.FromString,
                _registered_method=True)


class StatsServiceServicer(object):
    """── StatsService ─────────────────────────────────────────────────────────────

    """

    def QueryStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StatsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueryStats': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryStats,
                    request_deserializer=xray__api__pb2.QueryStatsRequest.FromString,
                    response_serializer=xray__api__pb2.QueryStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xray_api.StatsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('xray_api.StatsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StatsService(object):
    """── StatsService ─────────────────────────────────────────────────────────────

    """

    @staticmethod
    def QueryStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xray_api.StatsService/QueryStats',
            xray__api__pb2.QueryStatsRequest.SerializeToString,
            xray__api__pb2.QueryStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
